---
apiVersion: v1
kind: Service
metadata:
  name: testapp
  namespace: default
spec:
  selector:
    app: testapp
  type: NodePort
  ports:
    - name: testapp
      nodePort: 30523
      protocol: TCP
      port: 5000
      targetPort: 5000
